# Generated by Django 3.2.8 on 2021-10-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_carts_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartsitems',
            options={'verbose_name': 'Item Producto', 'verbose_name_plural': 'Items Productos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcartsitems',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Item Producto'},
        ),
    ]
