# Generated by Django 3.2.8 on 2021-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20211031_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcarts',
            name='user',
        ),
        migrations.AddField(
            model_name='carts',
            name='prueba',
            field=models.CharField(max_length=10, null=True, verbose_name='prueba'),
        ),
        migrations.AddField(
            model_name='historicalcarts',
            name='prueba',
            field=models.CharField(max_length=10, null=True, verbose_name='prueba'),
        ),
    ]
