# Generated by Django 3.2.8 on 2021-10-31 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0004_auto_20211031_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcartsitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='historicalcartsitems',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcartsitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalcarts',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='CartsItems',
        ),
        migrations.DeleteModel(
            name='HistoricalCartsItems',
        ),
        migrations.DeleteModel(
            name='HistoricalInventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
