# Generated by Django 3.2.8 on 2021-10-31 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211025_2318'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0005_auto_20211031_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='prueba',
        ),
        migrations.RemoveField(
            model_name='historicalcarts',
            name='prueba',
        ),
        migrations.CreateModel(
            name='HistoricalCartsItems',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('movement', models.CharField(choices=[('+', 'Ingreso'), ('-', 'Egreso')], default='+', max_length=1, verbose_name='Movimiento(+/-)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carts.carts')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.products')),
            ],
            options={
                'verbose_name': 'historical Item Producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CartsItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('movement', models.CharField(choices=[('+', 'Ingreso'), ('-', 'Egreso')], default='+', max_length=1, verbose_name='Movimiento(+/-)')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.carts')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name': 'Item Producto',
                'verbose_name_plural': 'Items Productos',
            },
        ),
        migrations.AddField(
            model_name='carts',
            name='products_items',
            field=models.ManyToManyField(through='carts.CartsItems', to='products.Products', verbose_name='Productos Carrito'),
        ),
    ]
